---
# Setup infrastructure

- name: setup nodes
  hosts: nodes
  remote_user: controller
  sudo: yes
  roles:
    - git
  tasks:
    - name: checkout app from repository app directory
      git: repo=git@github.com:fenfe1/satin.git version=develop dest=/app accept_hostkey=yes
    - name: set permissions for app directory
      file: path=/app owner=app group=app recurse=yes state=directory

- name: setup nodes
  hosts: nodes
  remote_user: controller
  sudo: yes
  roles:
    - composer

- name: setup application
  hosts: nodes
  remote_user: app
  vars_prompt:
  - name: "app_api_username"
    prompt: "Enter API username"
    private: yes
  - name: "app_api_password"
    prompt: "Enter API password"
    private: yes
  tasks:
  - name: create credentials file
    template: src=templates/credentials_file.json.j2 dest=/app/.secret_credentials.json
